### ISSUE TITLE
add a good summary when uploading

### ISSUE THREAD

**Issue by dpriskorn** [Ammarpad/OutreachyProject#6]
hi, before you go ahead and upload anything, I would like you to make sure that the edits have a summary that makes it easy to find the code. 
E.g. link to Wikidata:Tools/ AmmarpadOutreachyProject or a link to this repo or similar, so everyone can see what code triggered the edit.

**Comment by Ammarpad** [comment]
Thank you @dpriskorn. I responded on wiki also, I will modify the scripts to include link to each approval page for each task. Each approval page contains a link to the relevant scripts, so I think it will better place to link to.

**Comment by dpriskorn** [comment]
SGTM :)
